---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: todos-backend

outputs:
- name: package-output

run:
  path: SpringBootVueApplication/ci/tasks/package.sh
